# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [master]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-west-2"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Generate Environment Variables File for Production
        run: |
          echo "REACT_APP_AXIOS_INSTANCE_BASEURL=$REACT_APP_AXIOS_INSTANCE_BASEURL" >> .env.production
          echo "REACT_APP_FIREBASE_APIKEY=$REACT_APP_FIREBASE_APIKEY" >> .env.production
          echo "REACT_APP_FIREBASE_APPID=$REACT_APP_FIREBASE_APPID" >> .env.production
          echo "REACT_APP_FIREBASE_AUTHDOMAIN=$REACT_APP_FIREBASE_AUTHDOMAIN" >> .env.production
          echo "REACT_APP_FIREBASE_DATABASEURL=$REACT_APP_FIREBASE_DATABASEURL" >> .env.production
          echo "REACT_APP_FIREBASE_MESSAGINGSENDERID=$REACT_APP_FIREBASE_MESSAGINGSENDERID" >> .env.production
          echo "REACT_APP_FIREBASE_PROJECTID=$REACT_APP_FIREBASE_PROJECTID" >> .env.production
          echo "REACT_APP_FIREBASE_STORAGEBUCKET=$REACT_APP_FIREBASE_STORAGEBUCKET" >> .env.production
          echo "REACT_APP_GOOGLE_CALLBACK=$REACT_APP_GOOGLE_CALLBACK" >> .env.production
          echo "REACT_APP_GOOGLE_CLIENTID=$REACT_APP_GOOGLE_CLIENTID" >> .env.production
          echo "REACT_APP_KAKAO_APPKEY=$REACT_APP_KAKAO_APPKEY" >> .env.production
          echo "REACT_APP_KAKAO_REDIRECT_URI=$REACT_APP_KAKAO_REDIRECT_URI" >> .env.production
          echo "REACT_APP_KAKAO_REST_API_KEY=$REACT_APP_KAKAO_REST_API_KEY" >> .env.production
          echo "REACT_APP_SENTRY_REACT_DSN=$REACT_APP_SENTRY_REACT_DSN" >> .env.production

        env:
          REACT_APP_AXIOS_INSTANCE_BASEURL: ${{ secrets.REACT_APP_AXIOS_INSTANCE_BASEURL }}
          REACT_APP_FIREBASE_APIKEY: ${{ secrets.REACT_APP_FIREBASE_APIKEY }}
          REACT_APP_FIREBASE_APPID: ${{ secrets.REACT_APP_FIREBASE_APPID }}
          REACT_APP_FIREBASE_AUTHDOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTHDOMAIN }}
          REACT_APP_FIREBASE_DATABASEURL: ${{ secrets.REACT_APP_FIREBASE_DATABASEURL }}
          REACT_APP_FIREBASE_MESSAGINGSENDERID: ${{ secrets.REACT_APP_FIREBASE_MESSAGINGSENDERID }}
          REACT_APP_FIREBASE_PROJECTID: ${{ secrets.REACT_APP_FIREBASE_PROJECTID }}
          REACT_APP_FIREBASE_STORAGEBUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGEBUCKET }}
          REACT_APP_GOOGLE_CALLBACK: ${{ secrets.REACT_APP_GOOGLE_CALLBACK }}
          REACT_APP_GOOGLE_CLIENTID: ${{ secrets.REACT_APP_GOOGLE_CLIENTID }}
          REACT_APP_KAKAO_APPKEY: ${{ secrets.REACT_APP_KAKAO_APPKEY }}
          REACT_APP_KAKAO_REDIRECT_URI: ${{ secrets.REACT_APP_KAKAO_REDIRECT_URI }}
          REACT_APP_KAKAO_REST_API_KEY: ${{ secrets.REACT_APP_KAKAO_REST_API_KEY }}
          REACT_APP_SENTRY_REACT_DSN: ${{ secrets.REACT_APP_SENTRY_REACT_DSN }}

      - name: yarn install
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CI: "" # 경고를 에러로 보지 않게 함

      - name: Deploy S3 # Upload build file to S3
        run: |
          aws s3 cp --recursive --region us-west-2 build s3://neonaduri.com
